export const INDUSTRIES = Object.freeze({
  SOFTWARE: "Software",
  INFORMATION_TECHNOLOGY: "Information Technology",
  FINANCE: "Finance",
  BANKING: "Banking",
  INSURANCE: "Insurance",
  HEALTHCARE: "Healthcare",
  EDUCATION: "Education",
  ECOMMERCE: "E-Commerce",
  TELECOMMUNICATION: "Telecommunication",
  MANUFACTURING: "Manufacturing",
  CONSULTING: "Consulting",
  AUTOMOTIVE: "Automotive",
  MEDIA: "Media",
  HOSPITALITY: "Hospitality",
  LOGISTICS: "Logistics",
  GOVERNMENT: "Government",
  OTHER: "Other",
});
